language: rust
rust: 1.41.0
script: ci/run.bash
cache:
    directories:
        - target
        - $HOME/ritual_temp_test_dir/test_full_run/workspace/target

matrix:
    include:
        -   os: linux
            dist: bionic
            env: QT_VERSION=5.9.7
        -   os: osx
            env: QT_VERSION=5.9.7
        -   os: windows
            env: QT_VERSION=5.9.7
            rust: 1.41.0-x86_64-pc-windows-msvc
        -   os: linux
            dist: bionic
            env: QT_VERSION=5.11.3
        -   os: osx
            env: QT_VERSION=5.11.3
        -   os: windows
            env: QT_VERSION=5.11.3
            rust: 1.41.0-x86_64-pc-windows-msvc
        -   os: linux
            dist: bionic
            env: QT_VERSION=5.12.2
        -   os: osx
            env: QT_VERSION=5.12.2
        -   os: windows
            env: QT_VERSION=5.12.2
            rust: 1.41.0-x86_64-pc-windows-msvc
        -   os: linux
            dist: bionic
            env: QT_VERSION=5.13.0
        -   os: osx
            env: QT_VERSION=5.13.0
        -   os: windows
            env: QT_VERSION=5.13.0
            rust: 1.41.0-x86_64-pc-windows-msvc
        -   os: linux
            dist: bionic
            env: QT_VERSION=5.14.1
        -   os: osx
            env: QT_VERSION=5.14.1
        -   os: windows
            env: QT_VERSION=5.14.1
            rust: 1.41.0-x86_64-pc-windows-msvc
